#!/bin/bash
set -e # Exit with nonzero exit code if anything fails

TITLE="$1"
TITLE_SHORT="${TITLE/\-js/}"
DESCRIPTION="$2"
GITHUB_ORGANIZATION="$3"

SCRIPT_PATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# Verify inputs
if [ -z "$TITLE" ]
then
    echo "Error: Enter a module name"
    exit 1
fi

if [ -z "$DESCRIPTION" ]
then
    echo "Error: Enter a module description"
    exit 1
fi

# Create Directory
if [ -d "$TITLE" ]; 
then
    echo "Error: Module $TITLE already exists"
	exit 1
fi

# Create directory
mkdir $TITLE

# Template path

TEMPLATE_PATH="$SCRIPT_PATH/template"

# Copy templates
cp -R "$TEMPLATE_PATH/." $TITLE

# Move into directory
cd $TITLE

# Process test.js template
sed -ie -e "s/{{title}}/$TITLE/" -e "s/\/\*{{title_short}}\*\//$TITLE_SHORT/g" -e "s/{{title_short}}/$TITLE_SHORT/g" -e "s/{{description}}/$DESCRIPTION/" "./src/test/test.js"
rm src/test/test.jse

# Process src/index.js template
sed -ie -e "s/{{title}}/$TITLE/" -e "s/\/\*{{title_short}}\*\//$TITLE_SHORT/g" -e "s/{{title_short}}/$TITLE_SHORT/g" -e "s/{{description}}/$DESCRIPTION/" "./src/index.js"
rm src/index.jse

# Process index.js template
sed -ie -e "s/{{title}}/$TITLE/" -e "s/\/\*{{title_short}}\*\//$TITLE_SHORT/g" -e "s/{{title_short}}/$TITLE_SHORT/g" -e "s/{{description}}/$DESCRIPTION/" "./index.js"
rm index.jse

# Process index.html template
sed -ie -e "s/{{title}}/$TITLE/" -e "s/{{title_short}}/$TITLE_SHORT/g" -e "s/{{description}}/$DESCRIPTION/" "./src/test/index.html"
rm src/test/index.htmle

# Process README template
sed -ie -e "s/{{title}}/$TITLE/" -e "s/{{title_short}}/$TITLE_SHORT/g" -e "s/{{description}}/$DESCRIPTION/" "./src/README.md"
rm src/README.mde

# Create symlink for README in root directory
ln -s src/README.md README.md


# Rename Templates
mv src/index.js "src/$TITLE_SHORT.js"
mv index.js "$TITLE_SHORT.js"
# mv src/test/test.js "src/test/$TITLE_SHORT-spec.js"

# Create root link into default version


#
# Add to GIT repository
#


# Initial commit
git init
git add -A
git commit -m "Module initialization"

# Create Repository in Github
hub create $GITHUB_ORGANIZATION/$TITLE --description="$DESCRIPTION" --homepage="https://$GITHUB_ORGANIZATION.github.io/$TITLE/src/test/"

git push -u origin HEAD

git push origin master

# Go to root directory and commit the new submodule
cd ../

git submodule add ../$TITLE.git $TITLE
git submodule init 

git add -A
git commit -m "Add module $TITLE"
git push

cd $TITLE



