#!/bin/bash
set -e # Exit with nonzero exit code if anything fails

# Verify that we're in the root directory
ROOT_FILE="`pwd`/.gitmodules";
if [ ! -f "$ROOT_FILE" ]; 
then
    echo "Error: Go to the root directory"
	exit 1
fi


GITHUB_ORGANIZATION="coins"

SCRIPT_PATH="$(dirname "$(readlink "$0")")/"


COMMAND="$1"
case $COMMAND in
    "create" )
        /bin/bash "$SCRIPT_PATH/moma_create" "$2" "$3" "$GITHUB_ORGANIZATION" ;;
    "delete" )
        /bin/bash "$SCRIPT_PATH/moma_delete" "$2" "$GITHUB_ORGANIZATION" ;;
esac


